// Used for the Key Customers / Key Stakeholders status dropdown
export const IMPORTANCE_STATUS_OPTIONS = ["Critical", "Most Important", "Very Important", "Important", "Neutral"];

// Used for the Key/Core Products & Services status dropdown
export const PRODUCT_SERVICE_STATUS_OPTIONS = ["Primary (Key & Core)", "Secondary", "Augmented (Not Primary)"];

export const INDUSTRIES = [
  "Agriculture, Forestry & Fishing",
  "Mining & Quarrying",
  "Oil & Gas",
  "Manufacturing",
  "Electricity, Gas & Water Supply",
  "Construction & Real Estate Development",
  "Wholesale & Retail Trade",
  "Transportation & Logistics",
  "Hospitality & Tourism",
  "Information & Communication Technology (ICT)",
  "Financial Services & Insurance",
  "Banking",
  "Microfinance & Development Finance",
  "Investment & Asset Management",
  "Real Estate & Property Management",
  "Professional, Scientific & Technical Services",
  "Management Consulting",
  "Legal Services",
  "Accounting & Auditing",
  "Education & Training",
  "Healthcare & Medical Services",
  "Pharmaceuticals & Life Sciences",
  "Social Services & NGO / Non-Profit",
  "Government & Public Administration",
  "Defence & Security",
  "Media & Entertainment",
  "Telecommunications",
  "Renewable Energy & Sustainability",
  "E-Commerce & Digital Services",
  "Aviation & Aerospace",
  "Maritime & Shipping",
  "Automotive",
  "Food & Beverage",
  "Fashion & Retail",
  "Sports & Recreation",
  "Architecture & Engineering",
  "Research & Development",
  "Human Resources & Staffing",
  "Marketing & Advertising",
  "Others",
];

export const SECTORS = [
  "Public Sector",
  "Private Sector",
  "Parastatal / State-Owned Enterprise",
  "Non-Governmental Organisation (NGO)",
  "Development Finance Institution (DFI)",
  "Cooperative",
  "Social Enterprise",
  "Multinational Corporation",
  "Small & Medium Enterprise (SME)",
  "Micro Enterprise",
  "Community-Based Organisation",
  "Faith-Based Organisation",
  "Others",
];
